# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scam', '0002_student_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='user',
            new_name='friendA',
        ),
        migrations.RenameField(
            model_name='friend',
            old_name='friend',
            new_name='friendB',
        ),
    ]
